resources:
- name: repository
  source:
    branch: master
    uri: https://github.com/futurice/terraform-examples.git
  type: git
#     # branch: master
#     # uri: https://github.com/JamesWoolfenden/packer-by-example.git
- name: cicd
  source:
    branch: main
    uri: https://github.com/imran-init/terraform_fmt_validate.git
  type: git
jobs:
- name: unit-test
  plan:
  - get: cicd
  - get: repository
  - task: terraform-fmt-validate
    # input_mapping: { repository: cicd }
    params:
      # valid values: (fmt|validate|''), the default empty value will build both types.
      OPERATION: "validate"
      DIRS: "aws"
      # FILES: "hcl2/ubuntu/variables.pkr.hcl"
    file: cicd/fmt_validate_task.yml
    # config:
    #   platform: linux
    #   image_resource:
    #     name: ""
    #     source:
    #       repository: hashicorp/packer
    #       tag: latest
    #     type: docker-image
    #   inputs:
    #   - name: cicd
    #   - name: repository
    #   # params:
    #   #   ACTION: ""
    #   #   FILES: ""
    #   run:
    #     args:
    #     - repository
    #     path: ./cicd/packer_validate.sh